{{- if eq .Values.storage.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "model-serving.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  {{- if .Values.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.storage.pvc.storageClassName | quote }}
  {{- end }}
{{- end }}
