apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # EDIT THIS: point to your GitHub remote after pushing
    repoURL: https://github.com/HoucineDev/argocd-litellm-kserve.git
    targetRevision: main
    path: apps
    directory:
      recurse: false
      # Exclude self (root-app.yaml) to avoid infinite reconcile loops
      exclude: 'root-app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
